import { useCallback, useEffect, useMemo, useState } from 'react';
import { Download, FileSpreadsheet } from 'lucide-react';
import type { AdminMonthResponse, StaffSummary } from '../../attendance/types';
import { documentId } from '../../attendance/types';
import { durationLabel, studioMonth } from '../../attendance/format';
import { api } from '../api/client';
import { AdminAlert, AdminButton, AdminCard, AdminLoadingState, AdminPageHeader, AdminTableSurface, adminFieldClass } from '../components/ui';

export function AttendanceReportsPage() {
  const [month, setMonth] = useState(studioMonth()); const [data, setData] = useState<AdminMonthResponse | null>(null); const [loading, setLoading] = useState(true); const [downloading, setDownloading] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await api.attendanceMonthly(month)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Could not preview report.'); } finally { setLoading(false); } }, [month]);
  useEffect(() => { void load(); }, [load]);
  const rows = useMemo(() => aggregate(data), [data]); const unresolved = rows.reduce((sum, row) => sum + row.unresolved, 0);
  const download = async () => { setDownloading(true); setError(''); try { const blob = await api.attendanceCsv(month); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `attendance-${month}.csv`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); } catch (downloadError) { setError(downloadError instanceof Error ? downloadError.message : 'Could not download report.'); } finally { setDownloading(false); } };
  return <div className="mx-auto max-w-7xl space-y-6"><AdminPageHeader eyebrow="People" title="Monthly Attendance Report" description="Preview totals and download a basic CSV generated directly by the backend." actions={<AdminButton onClick={() => void download()} disabled={downloading}><Download className="h-4 w-4" />{downloading ? 'Preparing…' : 'Download CSV'}</AdminButton>} />{error && <AdminAlert>{error}</AdminAlert>}{unresolved > 0 && <AdminAlert tone="warning"><strong>{unresolved} unresolved attendance exception{unresolved === 1 ? '' : 's'}.</strong> The CSV can still be downloaded and includes an unresolved column.</AdminAlert>}<AdminCard className="p-4"><label className="block max-w-xs text-sm font-semibold text-admin-secondary">Report month<input type="month" className={adminFieldClass} value={month} onChange={(event) => setMonth(event.target.value)} /></label></AdminCard>{loading ? <AdminCard><AdminLoadingState label="Preparing preview…" /></AdminCard> : rows.length ? <AdminTableSurface><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b border-admin-border bg-admin-muted text-xs uppercase text-admin-subtle"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Present</th><th className="px-4 py-3">Field</th><th className="px-4 py-3">Leave</th><th className="px-4 py-3">Off / holiday</th><th className="px-4 py-3">LOP</th><th className="px-4 py-3">Late</th><th className="px-4 py-3">Missing</th><th className="px-4 py-3">Overtime</th><th className="px-4 py-3">Net hours</th><th className="px-4 py-3">Unresolved</th></tr></thead><tbody className="divide-y divide-admin-border">{rows.map((row) => <tr key={documentId(row.staff)}><td className="px-4 py-4"><p className="font-semibold">{row.staff.name}</p><p className="text-xs text-admin-subtle">{row.staff.employeeCode}</p></td><td className="px-4 py-4">{row.present}</td><td className="px-4 py-4">{row.field}</td><td className="px-4 py-4">{row.leave}</td><td className="px-4 py-4">{row.off}</td><td className="px-4 py-4 font-semibold text-red-700">{row.lop}</td><td className="px-4 py-4">{row.late}</td><td className="px-4 py-4">{row.missing}</td><td className="px-4 py-4">{durationLabel(row.overtime)}</td><td className="px-4 py-4 font-semibold">{durationLabel(row.net)}</td><td className="px-4 py-4">{row.unresolved}</td></tr>)}</tbody></table></AdminTableSurface> : <AdminCard className="p-10 text-center"><FileSpreadsheet className="mx-auto h-8 w-8 text-admin-subtle" /><p className="mt-3 text-sm text-admin-subtle">No attendance data for this month.</p></AdminCard>}</div>;
}

function aggregate(data: AdminMonthResponse | null) {
  const map = new Map<string, { staff: StaffSummary; present: number; field: number; leave: number; off: number; lop: number; late: number; missing: number; overtime: number; net: number; unresolved: number }>();
  (data?.rows || []).forEach((day) => { const staff = typeof day.staffAccountId === 'object' ? day.staffAccountId : ({ id: String(day.staffAccountId || ''), name: 'Staff' } as StaffSummary); const id = documentId(staff); const item = map.get(id) || { staff, present: 0, field: 0, leave: 0, off: 0, lop: 0, late: 0, missing: 0, overtime: 0, net: 0, unresolved: 0 }; if (day.status === 'PRESENT') item.present += 1; if (day.status === 'FIELD_WORK') item.field += 1; if (['ON_LEAVE', 'HALF_DAY_LEAVE'].includes(day.status)) item.leave += 1; if (['SCHEDULED_OFF', 'HOLIDAY'].includes(day.status)) item.off += 1; if (['LOSS_OF_PAY', 'ABSENT'].includes(day.status)) item.lop += 1; if (day.flags?.includes('LATE')) item.late += 1; if (day.flags?.includes('MISSING_PUNCH_OUT')) item.missing += 1; item.overtime += day.approvedOvertimeMinutes || 0; item.net += day.netMinutes || 0; if (day.unresolved) item.unresolved += 1; map.set(id, item); });
  return [...map.values()].sort((a, b) => a.staff.name.localeCompare(b.staff.name));
}
