import { CalendarCheck, Check, CircleDollarSign, MessageCircle, PhoneCall, Plus } from 'lucide-react';

const steps = [
  { icon: Plus, title: '1. Add every new customer', text: 'Tap the blue + button. Enter name and phone. Add a follow-up time if they need a reply later.', example: 'Add enquiry → Name → Phone → Save' },
  { icon: PhoneCall, title: '2. Contact the customer', text: 'Open Today or Enquiries. Tap Call or WhatsApp. After talking, set the next follow-up.', example: 'Call → Add follow-up → Save' },
  { icon: Check, title: '3. Finish a follow-up', text: 'Tap Done when the conversation is complete. Tap Tomorrow when the customer asks you to call later.', example: 'Done ✓  or  Tomorrow ↻' },
  { icon: CalendarCheck, title: '4. Confirm the booking', text: 'Open the enquiry and tap Convert. Choose the confirmed shoot date. Customer details are copied automatically.', example: 'Convert → Booking date → Confirm booking' },
  { icon: CircleDollarSign, title: '5. Record money received', text: 'Open Payments, find the customer, tap Record, enter the amount and payment method, then save.', example: 'Payments → Record → Amount → Save' },
];

export function HelpPage() {
  return <div className="mx-auto max-w-3xl space-y-5"><header className="rounded-2xl bg-blue-600 p-6 text-white"><div className="flex items-center gap-3"><MessageCircle className="h-7 w-7" /><div><p className="text-sm font-semibold text-blue-100">Doll Pictures quick guide</p><h1 className="text-2xl font-bold">Every new customer goes into Enquiries first.</h1></div></div><p className="mt-3 text-sm leading-6 text-blue-50">Use Today every morning. Complete items from top to bottom. Telegram links open the correct customer directly.</p></header><div className="space-y-4">{steps.map(({ icon: Icon, title, text, example }) => <section key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon className="h-5 w-5" /></span><div><h2 className="font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div></div><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4 text-center text-sm font-semibold text-slate-700" aria-label={`Example screen for ${title}`}>{example}</div></section>)}</div><section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">For the first week</h2><p className="mt-2 text-sm leading-6 text-amber-900">Check the paper diary and website together every evening. Enter only upcoming shoots, unpaid balances, and pending follow-ups. After one clean week, use the website as the main record.</p></section></div>;
}
