import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertCircle, IndianRupee, MessageCircle, Phone } from 'lucide-react';
import { api } from '../api/client';
import { whatsappUrl } from '../contact';
import type { Booking, PaymentMethod } from '../types';
import { AdminButton, AdminField, AdminModal, AdminPageHeader, adminFieldClass } from '../components/ui';

export function PaymentsPage() {
  const [items, setItems] = useState<Booking[]>([]);
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<Booking | null>(null);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setItems(await api.getBookings({ outstanding: true })); } catch (err) { setError(err instanceof Error ? err.message : 'Could not load payments.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => { const q = search.toLowerCase().trim(); return items.filter(item => !q || `${item.customerName} ${item.customerPhone}`.toLowerCase().includes(q)); }, [items, search]);
  return <div className="mx-auto max-w-4xl space-y-5"><AdminPageHeader eyebrow="Sales & Finance" title="Payments" description="Record money received while the customer is with you." />{error && <div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle className="h-5 w-5" />{error}</div>}{success && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{success}</div>}<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search customer or phone" className="h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-base" />{loading ? <div className="p-10 text-center text-slate-500">Loading payments…</div> : <div className="space-y-3">{visible.map(item => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><IndianRupee className="h-5 w-5" /></span><div className="min-w-0 flex-1"><h2 className="truncate font-semibold text-slate-900">{item.customerName}</h2><p className="mt-1 text-sm text-slate-500">Paid {money(item.paymentSummary.amountPaid)} · Balance <strong className="text-slate-800">{money(item.paymentSummary.balanceDue || 0)}</strong></p>{item.paymentDueDate && <p className="mt-1 text-xs text-slate-400">Due {item.paymentDueDate}</p>}</div></div><div className="mt-4 grid grid-cols-4 gap-2"><a href={`tel:${item.customerPhone}`} className="action"><Phone className="h-4 w-4" /> Call</a><a href={whatsappUrl(item.customerPhone)} target="_blank" rel="noreferrer" className="action text-emerald-700"><MessageCircle className="h-4 w-4" /> WhatsApp</a><Link to={`/admin/bookings/${item.id}`} className="action">Open</Link><button onClick={() => setSelected(item)} className="action bg-blue-600 text-white">Record</button></div></article>)}{!visible.length && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No outstanding payments.</div>}</div>}{selected && <PaymentModal booking={selected} onClose={() => setSelected(null)} onSaved={saved => { setSelected(null); setSuccess(`Payment recorded for ${saved.customerName}.`); setItems(current => saved.paymentSummary.balanceDue && saved.paymentSummary.balanceDue > 0 ? current.map(item => item.id === saved.id ? saved : item) : current.filter(item => item.id !== saved.id)); }} />}</div>;
}

function PaymentModal({ booking, onClose, onSaved }: { booking: Booking; onClose: () => void; onSaved: (booking: Booking) => void }) { const [amount, setAmount] = useState(String(booking.paymentSummary.balanceDue || '')); const [method, setMethod] = useState<PaymentMethod>('upi'); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const save = async () => { if (!(Number(amount) > 0)) return setError('Enter the amount received.'); setSaving(true); try { onSaved(await api.addBookingPayment(booking.id, { amount: Number(amount), paidAt: new Date().toISOString(), method })); } catch (err) { setError(err instanceof Error ? err.message : 'Could not record the payment.'); setSaving(false); } }; return <AdminModal open title="Record payment" description={booking.customerName} onClose={onClose} maxWidth="max-w-md" footer={<div className="grid grid-cols-2 gap-3"><AdminButton variant="secondary" onClick={onClose}>Cancel</AdminButton><AdminButton disabled={saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save payment'}</AdminButton></div>}>{error && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="space-y-4"><AdminField label="Amount received (₹)"><input autoFocus type="number" min="1" value={amount} onChange={e => setAmount(e.target.value)} className={adminFieldClass} /></AdminField><AdminField label="Payment method"><select value={method} onChange={e => setMethod(e.target.value as PaymentMethod)} className={adminFieldClass}><option value="upi">UPI</option><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select></AdminField></div></AdminModal>; }
function money(value: number) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value); }
