import { useEffect, useState } from 'react';
import { Plus, UserCog, X } from 'lucide-react';
import { api } from '../api/client';
import type { User } from '../types';
import { AdminButton, AdminPageHeader } from '../components/ui';

export function UsersPage() {
  const [users, setUsers] = useState<User[]>([]);
  const [adding, setAdding] = useState(false);
  const [error, setError] = useState('');
  const load = async () => { try { setUsers(await api.getAdminUsers()); } catch (err) { setError(err instanceof Error ? err.message : 'Could not load staff accounts.'); } };
  useEffect(() => { void load(); }, []);
  const toggle = async (user: User) => { try { const saved = await api.updateAdminUser(user.id, { isActive: !user.isActive }); setUsers(current => current.map(item => item.id === saved.id ? saved : item)); } catch (err) { setError(err instanceof Error ? err.message : 'Could not update the account.'); } };
  const reset = async (user: User) => { const temporaryPassword = window.prompt(`Enter a temporary password for ${user.name} (at least 8 characters)`); if (!temporaryPassword) return; try { const saved = await api.resetAdminUserPassword(user.id, temporaryPassword); setUsers(current => current.map(item => item.id === saved.id ? saved : item)); } catch (err) { setError(err instanceof Error ? err.message : 'Could not reset the password.'); } };
  return <div className="mx-auto max-w-4xl space-y-5"><AdminPageHeader eyebrow="Studio Settings" title="Staff accounts" description="Give each operations staff member their own login." actions={<AdminButton onClick={() => setAdding(true)}><Plus className="h-4 w-4" />Add staff</AdminButton>} />{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="space-y-3">{users.map(user => <article key={user.id} className="flex flex-wrap items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><UserCog className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="font-semibold text-slate-900">{user.name}</p><p className="truncate text-sm text-slate-500">{user.email} · {user.role}{user.mustChangePassword ? ' · password change pending' : ''}</p></div><button onClick={() => void reset(user)} className="h-10 rounded-xl border border-slate-300 px-3 text-sm font-semibold text-slate-700">Reset password</button><button onClick={() => void toggle(user)} className={`h-10 rounded-xl px-3 text-sm font-semibold ${user.isActive ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-200 text-slate-600'}`}>{user.isActive ? 'Active' : 'Inactive'}</button></article>)}</div>{adding && <AddUserModal onClose={() => setAdding(false)} onSaved={user => { setUsers(current => [...current, user]); setAdding(false); }} />}</div>;
}

function AddUserModal({ onClose, onSaved }: { onClose: () => void; onSaved: (user: User) => void }) { const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<User['role']>('operations'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const save = async () => { setSaving(true); try { onSaved(await api.createAdminUser({ name, email, temporaryPassword: password, role })); } catch (err) { setError(err instanceof Error ? err.message : 'Could not create the account.'); setSaving(false); } }; const input = 'mt-1 h-12 w-full rounded-xl border border-slate-300 px-3'; return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Add staff account</h2><button onClick={onClose} className="h-11 w-11"><X className="mx-auto h-5 w-5" /></button></div>{error && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="mt-4 block text-sm font-semibold">Name<input className={input} value={name} onChange={e => setName(e.target.value)} /></label><label className="mt-4 block text-sm font-semibold">Email<input type="email" className={input} value={email} onChange={e => setEmail(e.target.value)} /></label><label className="mt-4 block text-sm font-semibold">Temporary password<input type="password" className={input} value={password} onChange={e => setPassword(e.target.value)} /></label><label className="mt-4 block text-sm font-semibold">Access<select className={input} value={role} onChange={e => setRole(e.target.value as User['role'])}><option value="operations">Daily work only</option><option value="owner">Owner — full CMS</option></select></label><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={onClose} className="h-12 rounded-xl border border-slate-300 font-semibold">Cancel</button><button disabled={saving} onClick={() => void save()} className="h-12 rounded-xl bg-blue-600 font-semibold text-white disabled:opacity-50">{saving ? 'Creating…' : 'Create account'}</button></div></div></div>; }
