/**
 * Admin types — re-export shared CMS domain types.
 * Prefer importing from here inside `/admin` so paths stay stable.
 */
export type {
  AuthState,
  BehindScene,
  Booking,
  BookingStatus,
  BookingWritePayload,
  BookingPayment,
  PaymentMethod,
  PaymentState,
  PaymentSummary,
  WhatsAppMessageSummary,
  Category,
  Enquiry,
  EnquiryStage,
  EnquirySource,
  AdminEnquiryWritePayload,
  ConvertEnquiryPayload,
  HeroSlide,
  LocationType,
  ImageTransform,
  Package,
  PackageCategory,
  Photo,
  PricingMode,
  ServiceNavLink,
  SiteContent,
  Stat,
  StoryScene,
  TeamMember,
  Testimonial,
  User,
  TodayWork,
  TodayFollowUp,
  TodaySummaryItem,
  TodayPaymentItem,
  GoogleCalendarIntegrationStatus,
  WeeklyOwnerReport,
  AdminSearchItem,
  AdminSearchResponse,
  CustomerLookupRecord,
  CustomerLookupResponse,
  VoiceNoteSummary,
} from '../../shared/types';
