import { useCallback, useEffect, useState } from 'react';
import { RefreshCw, WalletCards } from 'lucide-react';
import { employeeApi, type EmployeeSalaryTransaction, type EmployeeSalarySummary } from '../api';
import { EmployeeAlert, EmployeeCard, EmployeeLoading, EmployeePageHeader } from '../components/EmployeeUi';
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value || 0);
const year = new Date().getFullYear();
export function EmployeeSalaryPage() {
  const [from, setFrom] = useState(`${year}-01-01`); const [to, setTo] = useState(`${year}-12-31`); const [rows, setRows] = useState<EmployeeSalaryTransaction[]>([]); const [summary, setSummary] = useState<EmployeeSalarySummary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [transactions, totals] = await Promise.all([employeeApi.salaryTransactions(from, to), employeeApi.salarySummary(from, to)]); setRows(transactions.transactions); setSummary(totals); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load salary history.'); } finally { setLoading(false); } }, [from, to]);
  useEffect(() => { void load(); }, [load]);
  return <div className="space-y-5"><EmployeePageHeader title="My Salary" description="Your recorded salary payments and selected-period total." action={<button type="button" onClick={() => void load()} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600" aria-label="Refresh"><RefreshCw className="h-4 w-4" /></button>} />{error && <EmployeeAlert>{error}</EmployeeAlert>}<EmployeeCard className="p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">From<input type="date" className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 px-3" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label className="text-sm font-semibold">To<input type="date" className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 px-3" value={to} onChange={(e) => setTo(e.target.value)} /></label></div></EmployeeCard>{loading ? <EmployeeLoading label="Loading salary history…" /> : <><div className="grid gap-3 sm:grid-cols-2"><EmployeeCard className="bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Selected period</p><p className="mt-2 text-2xl font-bold">{money(summary?.total || 0)}</p><p className="mt-1 text-sm text-slate-400">{summary?.transactionCount || 0} payment(s)</p></EmployeeCard><EmployeeCard className="p-5"><WalletCards className="h-6 w-6 text-blue-700" /><p className="mt-3 text-sm text-slate-500">Every weekly, monthly, advance, or shoot payment appears separately.</p></EmployeeCard></div>{rows.length === 0 ? <EmployeeCard className="p-8 text-center"><WalletCards className="mx-auto h-8 w-8 text-slate-300" /><h2 className="mt-3 font-bold">No salary records</h2><p className="mt-1 text-sm text-slate-500">Your owner will add payments here when they are recorded.</p></EmployeeCard> : <div className="space-y-3">{rows.map((row) => <EmployeeCard key={row.id} className="flex items-center justify-between gap-3 p-4"><div><p className="font-bold">{row.type.charAt(0).toUpperCase() + row.type.slice(1)} payment</p><p className="mt-1 text-xs text-slate-500">{row.transactionDate}{row.periodMonth ? ` · payroll ${row.periodMonth}` : ''}{row.note ? ` · ${row.note}` : ''}</p></div><p className="font-bold text-emerald-700">{money(row.amount)}</p></EmployeeCard>)}</div>}</>}</div>;
}
